##
# Copyright 2012 Yummy Melon Software LLC
# Author: Charles Y. Choi

doc:
	pydoc -w sequenceplot
	pydoc -w sequenceplot.SequenceObject
	pydoc -w sequenceplot.Actor
	pydoc -w sequenceplot.Placeholder
	pydoc -w sequenceplot.SequenceDiagram
